# Configuración de SonarQube para el proyecto ClinicaDental
sonar.projectKey=Sesion1-Despliege
sonar.projectName=Sesion1-Despliege
sonar.projectVersion=1.0
sonar.sources=.
sonar.host.url=http://127.0.0.1:9000
# Reemplaza TU_TOKEN_AQUI con el token generado en SonarQube (My Account -> Security -> Tokens)
sonar.login=sqp_87c0737949f8a28b32f5baf7f924032c749c1c58